<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div id="box"></div>
<script>
    function loadImg(url) {
        return new Promise((resolve,reject)=>{
            let img = new Image();//创建一个img实例
            img.src = url;
            img.onload = function () {//img一旦触发onload事件，就表示成功
                resolve(img);//成功的话，就拿到这个img，并且执行then方法的第一个回调函数
            };
            img.onerror = function (e) {//img一旦触发onerror事件，就表示失败
                reject(e);//失败的话，就拿到错误信息，并且执行then方法的第二个回调函数
            }
        })
    }

    //catch方法用来捕获错误信息，在then方法中不写第二个回调函数，而是用catch来捕获错误信息
    //删掉url的部分字段，在浏览器控制台来看catch到的错误信息
    loadImg("https://ss0.bdstatic.com/70cFvHSh_Q1YnxGkpoWK1HF6hhy/" +
        "it/u=528967148,228759238&fm=27&gp=0.jpg").then((img)=>{
            box.appendChild(img)
        //catch也可以找到then方法中的错误 去掉下面两句的注释控制台查看错误
            // let a;
            // let a;
        }).catch((e)=>{
        //捕获错误的，如果new promise中有错误会被捕获，如果then中的回调函数有错误也会被捕获
        console.log(e);
    })
</script>
</body>
</html>